blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Nexgent-ai/nexgent-open-source-trading-engine#readme
    about: Check our documentation before opening an issue
  - name: Discussions
    url: https://github.com/Nexgent-ai/nexgent-open-source-trading-engine/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
